name: Build and Push Docker Image to Docker Hub on Master

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: firestx # Replace with your Docker Hub username
  IMAGE_NAME: lume-server-container                 # Replace with your desired image name

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add this step to set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Use the latest version, v3 as of now

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=sha,prefix=,suffix=,event=branch,enable=${{ github.ref == 'refs/heads/master' }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Use the latest version, v5 as of now
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # These cache settings should now work correctly
          cache-from: type=gha
          cache-to: type=gha,mode=max # 'mode=max' includes all layers, good for GHA cache
